"""Deterministic, source-grounded fertilizer guidance for Burkina Faso crops.

The doses below are NOT generated by the LLM. They are fixed values taken from
published Burkina Faso research / extension recommendations (INERA and peer-
reviewed Burkinabè journals), so the assistant never invents fertilizer numbers.
Each crop entry cites the source(s) backing its figures, and every answer ends
with a mandatory "confirmez avec votre agent" disclaimer.

Sources:
  - Int. J. Biol. Chem. Sci. (IJBCS), essais microdose INERA sur sorgho, mil et
    niébé au Burkina Faso — dose vulgarisée céréales : 100 kg/ha NPK (14-23-14)
    + 50 kg/ha urée ; niébé : 100 kg/ha NPK seul.
  - Revue Sciences et Techniques du Burkina — dose vulgarisée maïs : 150 kg/ha
    NPK (14-23-14) + 100 kg/ha urée ; fertilisation des légumineuses (arachide,
    niébé) : faible apport d'azote (~14 kg N/ha) suffisant, fumure organique
    recommandée.
"""

SRC_IJBCS = "Recherche INERA — Int. J. Biol. Chem. Sci. (microdose Burkina)"
SRC_RSTB_MAIS = "Rev. Sciences et Techniques du Burkina (dose vulgarisée maïs)"
SRC_RSTB_LEG = "Rev. Sciences et Techniques du Burkina (fertilisation légumineuses)"

DISCLAIMER = (
    "⚠️ Ce sont des recommandations générales issues de la recherche (INERA). "
    "Confirmez toujours avec votre agent agricole : la bonne dose dépend de votre "
    "sol, de la pluie et de vos moyens."
)

# Canonical crop -> grounded recommendation text + sources.
_RECOMMENDATIONS = {
    "sorgho": {
        "lines": [
            "Dose vulgarisée : 100 kg/ha de NPK (14-23-14) au semis + 50 kg/ha "
            "d'urée (46 %) à la montaison.",
            "Microdose (plus économique) : 2 g de NPK par poquet (~62,5 kg/ha) au "
            "semis + 1 g d'urée par poquet (~31,25 kg/ha) à la montaison.",
        ],
        "sources": [SRC_IJBCS],
    },
    "mil": {
        "lines": [
            "Dose vulgarisée : 100 kg/ha de NPK (14-23-14) au semis + 50 kg/ha "
            "d'urée (46 %) à la montaison.",
            "Microdose (plus économique) : 3 g de NPK par poquet (~62,5 kg/ha) au "
            "semis + 1,5 g d'urée par poquet (~46,88 kg/ha) à la montaison.",
        ],
        "sources": [SRC_IJBCS],
    },
    "maïs": {
        "lines": [
            "Dose vulgarisée : 150 kg/ha de NPK (14-23-14) au semis + 100 kg/ha "
            "d'urée (46 %) en couverture.",
            "Le maïs est très exigeant : un sol pauvre donne de faibles rendements. "
            "La fumure organique et la rotation aident beaucoup.",
        ],
        "sources": [SRC_RSTB_MAIS],
    },
    "niébé": {
        "lines": [
            "Dose vulgarisée : 100 kg/ha de NPK (14-23-14), sans urée — le niébé "
            "est une légumineuse qui fixe l'azote de l'air.",
            "Un faible apport d'azote suffit ; la fumure organique améliore le "
            "rendement.",
        ],
        "sources": [SRC_IJBCS, SRC_RSTB_LEG],
    },
    "arachide": {
        "lines": [
            "L'arachide est une légumineuse : elle fixe l'azote de l'air, donc un "
            "faible apport d'azote (~14 kg N/ha) suffit.",
            "Privilégiez la fumure organique (fumier) et le phosphate ; évitez les "
            "fortes doses d'urée.",
        ],
        "sources": [SRC_RSTB_LEG],
    },
}

# Correct French article per crop (for "pour ... au Burkina Faso").
_CROP_LABEL = {
    "sorgho": "le sorgho",
    "mil": "le mil",
    "maïs": "le maïs",
    "niébé": "le niébé",
    "arachide": "l'arachide",
}

# Surface forms -> canonical crop key.
_CROP_ALIASES = {
    "sorgho": "sorgho",
    "sorghum": "sorgho",
    "mil": "mil",
    "millet": "mil",
    "petit mil": "mil",
    "maïs": "maïs",
    "mais": "maïs",
    "maize": "maïs",
    "niébé": "niébé",
    "niebe": "niébé",
    "cowpea": "niébé",
    "haricot": "niébé",
    "arachide": "arachide",
    "arachides": "arachide",
    "groundnut": "arachide",
    "cacahuète": "arachide",
    "cacahuete": "arachide",
}

# Words that signal the user is asking about fertilizer / fertilization.
_FERTILIZER_KEYWORDS = (
    "engrais",
    "fumure",
    "fertilis",
    "npk",
    "urée",
    "uree",
    "dose d'engrais",
    "dose d engrais",
    "fertilizer",
    "microdose",
    "micro-dose",
)


def is_fertilizer_query(text: str) -> bool:
    """True if the question is about fertilizer/fertilization."""
    t = (text or "").lower()
    return any(kw in t for kw in _FERTILIZER_KEYWORDS)


def _match_crop(text: str) -> str | None:
    """Return the canonical crop mentioned in the text, or None."""
    t = (text or "").lower()
    # Check multi-word aliases first (e.g. "petit mil") for a more specific match.
    for alias in sorted(_CROP_ALIASES, key=len, reverse=True):
        if alias in t:
            return _CROP_ALIASES[alias]
    return None


def get_fertilizer_advice(text: str) -> dict | None:
    """Return grounded fertilizer advice for the crop in the question.

    Returns a dict {"answer": str, "sources": list[str]} when a supported crop is
    detected, otherwise None (so the caller can fall back to RAG). The numbers are
    fixed/cited — never generated — and the answer always carries the disclaimer.
    """
    crop = _match_crop(text)
    if crop is None or crop not in _RECOMMENDATIONS:
        return None

    rec = _RECOMMENDATIONS[crop]
    body = "\n".join(f"• {line}" for line in rec["lines"])
    answer = (
        f"🌱 Fumure recommandée pour {_CROP_LABEL[crop]} au Burkina Faso :\n"
        f"{body}\n\n"
        f"{DISCLAIMER}"
    )
    return {"answer": answer, "sources": list(rec["sources"])}
